spring:
  application:
    name: ezgraph
  profiles:
    include: db

  jpa:
    show-sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl_auto: create
    database-platform: org.hibernate.dialect.MySQLDialect


logging:
  level:
    org:
      springframework: debug